version: "3.9"

services:
  api:
    build:
      context: ../
      dockerfile: docker/api.Dockerfile
      args:
        TURBO_TOKEN: ${TURBO_TOKEN}
    restart: always
    ports:
      - "${API_PORT:-3005}:3005"
    environment:
      - BASE_URL=${BASE_URL}
      - APP_PORT=${APP_PORT}
      - APP_ADDRESS=${APP_ADDRESS}
    container_name: api
    networks:
      - app_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=3005"

  web:
    build:
      context: ../
      dockerfile: docker/web.Dockerfile
      args:
        TURBO_TOKEN: ${TURBO_TOKEN}
    restart: always
    ports:
      - "${WEB_PORT:-3000}:3000"
    container_name: web
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_MAX_DAYS=${NEXT_PUBLIC_MAX_DAYS}
      - SESSION_PASSWORD=${SESSION_PASSWORD}
    depends_on:
      - api
    networks:
      - app_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/web`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=3000"

  # fe:
  #   build:
  #     context: ../
  #     dockerfile: docker/fe.Dockerfile
  #   ports:
  #     - "3006:3006"
  #   container_name: fe
  #   depends_on:
  #     - api
  #   networks:
  #     - app_net

networks:
  app_net:
    external: true
