version: "3.9"

services:
  api:
    build:
      context: ../
      dockerfile: docker/api.Dockerfile
    ports:
      - "3005:3005"
    container_name: api
    networks:
      - app_net

  web:
    build:
      context: ../
      dockerfile: docker/web.Dockerfile
    ports:
      - "3007:3007"
    container_name: web
    depends_on:
      - api
    networks:
      - app_net

  fe:
    build:
      context: ../
      dockerfile: docker/fe.Dockerfile
    ports:
      - "3006:3006"
    container_name: fe
    depends_on:
      - api
    networks:
      - app_net

networks:
  app_net:
